import type { ExtractedProductFields, LearningContext } from "../types/analysis";
import { createExtracted, createLearningContext } from "./analysis-fixtures";

export type AnalysisScenarioExpectation = {
  criticalKeywords: string[];
  firstSuggestionKeywords: string[];
  minSuggestions?: number;
  maxSuggestions?: number;
  topSignalKeywords?: string[];
};

export type AnalysisScenario = {
  name: string;
  description: string;
  extracted: ExtractedProductFields;
  learningContext: LearningContext;
  expected: AnalysisScenarioExpectation;
};

export function getOfflineAnalysisScenarios(): AnalysisScenario[] {
  return [
    {
      name: "delivery-case",
      description:
        "Kategori benchmarkina gore yavas teslimat ana darbozaga donusmeli.",
      extracted: createExtracted({
        shipping_days: 8,
        image_count: 4,
        has_video: false,
        official_seller: false,
        favorite_count: 600000,
        review_count: 80,
        review_summary: {
          sampled_count: 4,
          low_rated_count: 2,
          positive_count: 2,
          negative_count: 2,
        },
      }),
      learningContext: createLearningContext(),
      expected: {
        criticalKeywords: ["teslim"],
        firstSuggestionKeywords: ["teslim"],
        minSuggestions: 1,
        maxSuggestions: 5,
      },
    },
    {
      name: "stock-case",
      description: "Stok kesintisi varsa baska sinyallerin onune gecmeli.",
      extracted: createExtracted({
        stock_quantity: 0,
        stock_status: "stokta yok",
        has_add_to_cart: false,
        shipping_days: null,
        other_sellers_summary: null,
        other_sellers_count: 0,
      }),
      learningContext: createLearningContext({
        benchmark: null,
        rules: [],
      }),
      expected: {
        criticalKeywords: ["stok"],
        firstSuggestionKeywords: ["stok"],
        minSuggestions: 1,
        maxSuggestions: 5,
      },
    },
    {
      name: "content-case",
      description:
        "Detay sayfasi ikna zayifligi benchmark ve icerik sinyalleriyle one cikmali.",
      extracted: createExtracted({
        description_length: 60,
        bullet_point_count: 1,
        has_specs: false,
        has_video: false,
        favorite_count: 40000,
        other_sellers_summary: {
          count: 5,
          scored_count: 5,
          avg_score: 8.9,
          top_score: 9.4,
          official_count: 1,
          fast_delivery_count: 1,
          high_follower_count: 1,
          seller_names: ["A", "B", "C"],
          min_price: 999,
          max_price: 1120,
          avg_price: 1040,
          cheapest_seller_name: "A",
          same_price_count: 1,
          cheaper_count: 0,
          more_expensive_count: 4,
        },
      }),
      learningContext: createLearningContext(),
      expected: {
        criticalKeywords: ["aciklama", "detay", "icerik"],
        firstSuggestionKeywords: ["aciklama", "detay", "icerik"],
        minSuggestions: 1,
        maxSuggestions: 5,
      },
    },
    {
      name: "visual-case",
      description:
        "Benchmarka gore zayif gorsel vitrin kritik teshise cikmali.",
      extracted: createExtracted({
        image_count: 2,
        has_video: false,
        shipping_days: 2,
        description_length: 420,
        has_specs: true,
        favorite_count: 30000,
        review_count: 500,
        review_summary: null,
        other_sellers_summary: {
          count: 5,
          scored_count: 5,
          avg_score: 8.9,
          top_score: 9.4,
          official_count: 1,
          fast_delivery_count: 1,
          high_follower_count: 1,
          seller_names: ["A", "B", "C"],
          min_price: 990,
          max_price: 1100,
          avg_price: 1035,
          cheapest_seller_name: "A",
          same_price_count: 1,
          cheaper_count: 0,
          more_expensive_count: 4,
        },
      }),
      learningContext: createLearningContext(),
      expected: {
        criticalKeywords: ["gorsel", "vitrin"],
        firstSuggestionKeywords: ["gorsel", "vitrin"],
        minSuggestions: 1,
        maxSuggestions: 5,
      },
    },
    {
      name: "price-case",
      description:
        "Rakip ve benchmark ustu fiyat guven telafisi zayifsa ana darbozaga donusmeli.",
      extracted: createExtracted({
        normalized_price: 1649,
        original_price: 1899,
        official_seller: false,
        seller_score: 7.8,
        shipping_days: 2,
        favorite_count: 45000,
        review_count: 180,
        other_sellers_summary: {
          count: 6,
          scored_count: 6,
          avg_score: 8.8,
          top_score: 9.3,
          official_count: 1,
          fast_delivery_count: 2,
          high_follower_count: 2,
          seller_names: ["A", "B", "C"],
          min_price: 1099,
          max_price: 1520,
          avg_price: 1210,
          cheapest_seller_name: "A",
          same_price_count: 0,
          cheaper_count: 5,
          more_expensive_count: 0,
        },
      }),
      learningContext: createLearningContext(),
      expected: {
        criticalKeywords: ["fiyat", "rakip"],
        firstSuggestionKeywords: ["fiyat", "rakip"],
        minSuggestions: 1,
        maxSuggestions: 5,
      },
    },
    {
      name: "trust-case",
      description:
        "Satici guveni benchmark altina duserse kritik teshis guven temasina kaymali.",
      extracted: createExtracted({
        seller_score: 6.7,
        official_seller: false,
        has_return_info: false,
        shipping_days: 2,
        normalized_price: 1049,
        review_count: 220,
        favorite_count: 80000,
        other_sellers_summary: {
          count: 5,
          scored_count: 5,
          avg_score: 8.9,
          top_score: 9.5,
          official_count: 2,
          fast_delivery_count: 2,
          high_follower_count: 2,
          seller_names: ["A", "B", "C"],
          min_price: 1019,
          max_price: 1120,
          avg_price: 1060,
          cheapest_seller_name: "A",
          same_price_count: 1,
          cheaper_count: 1,
          more_expensive_count: 3,
        },
      }),
      learningContext: createLearningContext(),
      expected: {
        criticalKeywords: ["guven", "satici"],
        firstSuggestionKeywords: ["guven", "satici", "iade"],
        minSuggestions: 1,
        maxSuggestions: 5,
      },
    },
    {
      name: "review-case",
      description:
        "Ilgi yuksek ama yorum/sosyal kanit zayifsa sepet oncesi surtunme one cikmali.",
      extracted: createExtracted({
        shipping_days: 2,
        image_count: 10,
        description_length: 420,
        has_specs: true,
        seller_score: 9.1,
        official_seller: true,
        favorite_count: 650000,
        review_count: 20,
        review_summary: {
          sampled_count: 4,
          low_rated_count: 3,
          positive_count: 1,
          negative_count: 3,
        },
        other_sellers_summary: {
          count: 5,
          scored_count: 5,
          avg_score: 8.8,
          top_score: 9.2,
          official_count: 1,
          fast_delivery_count: 2,
          high_follower_count: 1,
          seller_names: ["A", "B", "C"],
          min_price: 999,
          max_price: 1100,
          avg_price: 1030,
          cheapest_seller_name: "A",
          same_price_count: 1,
          cheaper_count: 0,
          more_expensive_count: 4,
        },
      }),
      learningContext: createLearningContext(),
      expected: {
        criticalKeywords: ["guven", "sepet", "yorum"],
        firstSuggestionKeywords: ["sepet", "guven", "yorum"],
        minSuggestions: 1,
        maxSuggestions: 5,
        topSignalKeywords: ["sosyal kanit", "yorum"],
      },
    },
    {
      name: "low-data-case",
      description:
        "Kritik veri eksigi varsa analiz bunu acikca sinyalleyip korumali yorum kurmali.",
      extracted: createExtracted({
        title: null,
        meta_description: null,
        h1: null,
        brand: null,
        product_name: null,
        model_code: null,
        price: null,
        normalized_price: null,
        original_price: null,
        discount_rate: null,
        image_count: 1,
        has_video: false,
        rating_value: null,
        rating_breakdown: null,
        review_count: null,
        review_snippets: null,
        qa_snippets: null,
        review_summary: null,
        question_count: null,
        description_length: null,
        bullet_point_count: null,
        has_add_to_cart: false,
        has_shipping_info: false,
        has_free_shipping: false,
        shipping_days: null,
        has_return_info: false,
        has_specs: false,
        has_faq: false,
        variant_count: null,
        stock_quantity: null,
        stock_status: null,
        seller_name: null,
        merchant_id: null,
        listing_id: null,
        seller_badges: null,
        seller_score: null,
        follower_count: null,
        favorite_count: null,
        other_sellers_count: null,
        other_seller_offers: null,
        other_sellers_summary: null,
        has_brand_page: false,
        official_seller: false,
        has_campaign: false,
        campaign_label: null,
        promotion_labels: null,
        delivery_type: null,
        is_best_seller: false,
        best_seller_rank: null,
        best_seller_badge: null,
        extractor_status: "blocked",
      }),
      learningContext: createLearningContext({
        benchmark: null,
        rules: [],
        memorySnippets: [],
        systemLearning: null,
      }),
      expected: {
        criticalKeywords: ["veri", "eksik"],
        firstSuggestionKeywords: ["icerik", "aciklama"],
        minSuggestions: 1,
        maxSuggestions: 5,
        topSignalKeywords: ["kapsam", "eksik"],
      },
    },
  ];
}
